### PR TITLE
Corrected README Instructions

### PR DESCRIPTION
**Pull request by skinzer**
Corrected instructions for testing the tool. Currently the --gradle etc options are not working, so the README is updated until the problem can be fully fixed

### CODE REVIEW

**Comment by curphey** [comment]
Who has been assigned the task of fixing it ?

**Comment by skinzer** [comment]
I am not sure who is maintaining this anymore, so I wasn't sure who it should be assigned to. I can certainly take on the task if need be.

**Comment by codelion** [comment]
Ming can take a look and fix it so that the `--gradle` etc. options run with some default config file.

**Comment by newbishme** [comment]
Original intended usage of command line options has been implemented. Reverted the corrected instructions in README.

**Pull request merged**
